---
- name: Build etherpad-lite
  ansible.builtin.shell: |
    pnpm i
    pnpm run build:etherpad
  args:
    executable: /bin/bash
    chdir: "{{ etherpad_path }}"
  environment:
    NODE_ENV: "{{ etherpad_node_environment }}"
    PATH: "{{ etherpad_environment_path }}"
  become: true
  become_user: "{{ etherpad_user }}"
  check_mode: false
  changed_when: true
  notify: Restart etherpad-lite

- name: Restart etherpad-lite
  ansible.builtin.service:
    name: etherpad-lite
    state: restarted

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
